### ISSUE TITLE
Any shortcodes to use?

### ISSUE THREAD

**Issue by jgajera** [WPprodigy/WooCommerce-Product-Fees#28]
Hey there,
I have a multivendor marketplace website, and I wanted to see if there are any ready-to-use shortcodes to implement on front-end product templates.

Thanks!

**Comment by profesoryeow** [comment]
I need the same 👍 

(and I use not only single products, I use variations in products)

**Comment by jgajera** [comment]
Any updates? Assuming no, but my client has a rush deadline, so I figured I'd reach out again. Thank you, and Happy Friday!

**Comment by WPprodigy** [comment]
There aren't any shortcodes for this, sorry. Programmatically speaking, it isn't hard to display fee name/price data on every product page template though. Reach out to a freelance developer. Should take less than an hour.

Otherwise, you can just type out the fee info in the product short description?
