### ISSUE TITLE
Add support for decimal amounts with comma's

### ISSUE THREAD

**Issue by WPprodigy** [WPprodigy/WooCommerce-Product-Fees#9]
https://wordpress.org/support/topic/add-support-for-decimal-amounts-with-commas

**Comment by daigo75** [comment]
Personal opinion: it's perfectly acceptable to require figures entered with a point, in the backend (i.e. to expect admins to always enter 12**.**34). The fronted will format them automatically, respecting the locale.

Replacing commas with points can cause issues if, for any reason, the site is misconfigured to use the same separator for thousands and decimals (I've seen it happening).

Based on my experience, this feature can bring more headache than it's worth (been there, done that). :smile:

**Comment by WPprodigy** [comment]
Thanks for the input :). I'm thinking about just a quick conversion between commas and periods in the backend. Nothing else should be involved in messing with commas before the conversion happens.

**Comment by kleinermann** [comment]
Hi there,
First i'd like to say thanks for the great plugin. I use this plugin in Germany and we use a comma instead of a point for decimals.
Do i understand you right that you suggest to change the settings in WooCommerce to use a point instead of a comma for decimal separation?
If yes, this doesn't seem to be a great solution as it is not intuitive for site managers to add amounts with a dot.
Would it not be better to check what settings WooCommerce is using and then just use the same for the product fees?

**Comment by WPprodigy** [comment]
> it is not intuitive for site managers to add amounts with a dot.

Depends on where you are from ;)

> Would it not be better to check what settings WooCommerce is using and then just use the same for the product fees?

That's the plan

**Comment by kleinermann** [comment]
Ok, thanks for the feedback.
